export const createYatchFrom = [
  {
    type: 'text',
    name: 'name',
    id: 'f1',
    label: 'Yacth Name',
    colClass: 'col-sm-6 col-4',
    validation: {
      required: 'Yatch name is required',
    },
  },
  {
    type: 'select',
    name: 'typeid',
    id: 'f2',
    placeholder: 'Select Yatch Type',
    label: 'Yacth Type',
    valueKey: '_id',
    labelKey: 'typename',
    colClass: 'col-sm-6 col-4',
    dynamicOptionKey: 'yatchTypeOptions',
    validation: {
      required: 'Yatch type is required',
    },
  },
  {
    type: 'select',
    name: 'ownerid',
    id: 'fnew1',
    placeholder: 'Select Owner',
    label: 'Yacth Owner',
    customValueKey: '_id',
    valueKey: '_id',
    labelKey: 'name',
    colClass: 'col-sm-6 col-4',
    dynamicOptionKey: 'usersOptions',
    validation: {
      required: 'Yatch owner is required',
    },
  },
  {
    type: 'select',
    name: 'parenttypeid',
    id: 'f3',
    label: 'Parent Type',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'text',
    name: 'shortdescription',
    id: 'f4',
    label: 'Short Description',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'textArea',
    name: 'fulldescription',
    id: 'f5',
    label: 'Long Description',
    textAreaRow: '1',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'text',
    name: 'typename',
    id: 'f6',
    label: 'Type Name',
    colClass: 'col-sm-6 col-4',
  },
  // {
  //   type: 'text',
  //   name: 'ownerid',
  //   id: 'f6',
  //   label: 'Owner Id',
  //   colClass: "col-sm-6 col-4"
  // },
  {
    type: 'number',
    name: 'point',
    id: 'f9',
    label: '*Points',
    colClass: 'col-sm-6 col-4',
    validation: {
      required: 'Yatch point is required',
    },
  },
  {
    type: 'number',
    name: 'height',
    id: 'f10',
    label: 'Height',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'round-number',
    name: 'length',
    id: 'f23',
    label: 'Length',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'checkbox',
    name: 'showonhomepage',
    id: 'f7',
    label: 'Show on home page',
    colClass: 'col-sm-2 col-4',
  },
  {
    type: 'checkbox',
    name: 'isnew',
    id: 'f8',
    label: 'Is New',
    colClass: 'col-sm-2 col-4',
  },
  {
    type: 'checkbox',
    name: 'status',
    id: 'f12',
    label: 'status',
    colClass: 'col-sm-2 col-4',
  },
  {
    type: 'googlePlaceSearch',
    name: 'location',
    id: 'f21',
    label: '*Location',
    colClass: 'col-sm-6 col-4',
    customHandlerKey: 'handlePlaceSearch',
    validation: {
      required: 'Location is required',
    },
  },
]

export const overViewForm = [
  {
    type: 'text',
    name: 'builder',
    id: 'f1',
    label: 'Builder',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'date',
    name: 'refit',
    id: 'f2',
    label: 'Refit Date',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'number',
    name: 'sleeps',
    id: 'f3',
    label: 'Sleeps Count',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'text',
    name: 'winter',
    id: 'f4',
    label: 'Winter',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'round-number',
    name: 'length',
    id: 'f5',
    label: 'Length',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'number',
    name: 'crew',
    id: 'f6',
    label: 'Crew',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'text',
    name: 'summer',
    id: 'f9',
    label: 'Summer Destination',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'textArea',
    name: 'description',
    textAreaRow: '1',
    id: 'f10',
    label: 'Description',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'number',
    name: 'gustes',
    id: 'f24',
    label: 'Guests',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'text',
    name: 'staterooms',
    id: 'f12',
    label: 'State Rooms',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'number',
    name: 'year',
    id: 'f7',
    label: 'Year',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'multiInput',
    name: 'requirementsforthisBooking',
    id: 'f3',
    label: 'Requirments For Booking',
    colClass: 'col-sm-6 col-4',
    variableName: 'bookingRequirments',
    customHandlerKey: 'handleMultiInput',
  },
]

export const reviewForm = [
  { type: 'text', name: 'reviewtitle', label: 'Review Title', colClass: 'col-sm-6 col-4' },
  { type: 'text', name: 'username', label: 'User Name', colClass: 'col-sm-6 col-4' },
  { type: 'email', name: 'reviewerEmail', label: 'Email', colClass: 'col-sm-6 col-4' },
  { type: 'text', name: 'avathar', label: 'avathar', colClass: 'col-sm-6 col-4' },
  { type: 'date', name: 'reviewdate', label: 'Review Date', colClass: 'col-sm-6 col-4' },
]
export const yachtCrewForm = [
  { type: 'text', name: 'crewtitle', label: 'Crew Title', colClass: 'col-sm-6 col-4' },
  { type: 'text', name: 'crewdescription', label: 'Crew Description', colClass: 'col-sm-6 col-4' },
  // {
  //   type: 'multiInput',
  //   id: 'g8',
  //   name: 'members',
  //   label: 'Members',
  //   colClass: 'col-sm-6 col-4',
  // },
]
export const accomodationForm = [
  {
    type: 'text',
    name: 'accommodationdescription',
    label: 'Accomodation Description',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'multiInput',
    id: 'g3',
    name: 'accommodationfeatures',
    label: 'Accomodation Features',
    colClass: 'col-sm-6 col-4',
    variableName: 'accommodationfeatures',
    customHandlerKey: 'handleMultiInput',
  },
]

export const charteragentForm = [
  { type: 'text', name: 'name', label: 'Name', colClass: 'col-sm-6 col-4' },
  { type: 'text', name: 'position', label: 'Position', colClass: 'col-sm-6 col-4' },
  { type: 'number', name: 'displayorder', label: 'Display Order', colClass: 'col-sm-6 col-4' },
  { type: 'text', name: 'url', label: 'URL', colClass: 'col-sm-6 col-4' },
  { type: 'text', name: 'facebook', label: 'Facebook', colClass: 'col-sm-6 col-4' },
  { type: 'text', name: 'twitter', label: 'Twitter', colClass: 'col-sm-6 col-4' },
  { type: 'text', name: 'linkedin', label: 'LinkedIn', colClass: 'col-sm-6 col-4' },
  { type: 'text', name: 'youtube', label: 'Youtube', colClass: 'col-sm-6 col-4' },
]

export const specificationForm = [
  {
    type: 'text',
    name: 'specificationsdescription',
    id: 'sp1',
    label: 'Specification Description',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'number',
    name: 'sleeps',
    id: 'sp2',
    label: 'Sleeps',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'number',
    name: 'staterooms',
    id: 'sp3',
    label: 'State Rooms',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'number',
    name: 'heads',
    id: 'sp4',
    label: 'Heads',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'number',
    name: 'bkings',
    id: 'sp5',
    label: 'BKings(S)',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'number',
    name: 'queens',
    id: 'sp6',
    label: 'Queens',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'number',
    name: 'twins',
    id: 'sp7',
    label: 'Twins',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'text',
    name: 'loa',
    id: 'sp8',
    label: 'Loa',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'text',
    name: 'beam',
    id: 'sp9',
    label: 'Beam',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'text',
    name: 'maximumdraft',
    id: 'sp10',
    label: 'Maximum Draft',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'number',
    name: 'cruisingspeed',
    id: 'sp11',
    label: 'Crusing Speed',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'number',
    name: 'fueldetails',
    id: 'sp17',
    label: 'Fuel Details',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'number',
    name: 'generators',
    id: 'sp18',
    label: 'No of generators',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'text',
    name: 'enginestotalpower',
    id: 'sp19',
    label: 'Engine Total Power',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'select',
    name: 'enginefueltype',
    id: 'sp20',
    label: 'Engine Fuel Type',
    colClass: 'col-sm-6 col-4',
    options: [
      {
        label: 'Diesel',
        value: 'Diesel',
      },
      {
        label: 'Petrol',
        value: 'Petrol',
      },
    ],
  },
  {
    type: 'number',
    name: 'enginehours',
    id: 'sp21',
    label: 'Engine Hours',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'text',
    name: 'enginetype',
    id: 'sp22',
    label: 'Engine Speed',
    colClass: 'col-sm-3 col-4',
  },
  {
    type: 'text',
    name: 'enginemodel',
    id: 'sp23',
    label: 'Engine Model',
    colClass: 'col-sm-3 col-4',
  },
  {
    type: 'text',
    name: 'enginebrand',
    id: 'sp24',
    label: 'Engine Brand',
    colClass: 'col-sm-3 col-4',
  },
  {
    type: 'text',
    name: 'engine',
    id: 'sp25',
    label: 'Engine',
    colClass: 'col-sm-3 col-4',
  },
  {
    type: 'checkbox',
    name: 'jacuzzi',
    id: 'sp12',
    label: 'Jacuzzi',
    colClass: 'col-sm-6 col-4',
    onTrue: 'Yes',
    onFalse: 'No',
  },
  {
    type: 'checkbox',
    name: 'helicopterpad',
    id: 'sp13',
    label: 'Helicoptor Pad',
    colClass: 'col-sm-6 col-4',
    onTrue: 'Yes',
    onFalse: 'No',
  },
  {
    type: 'checkbox',
    name: 'bbq',
    id: 'sp14',
    label: 'BBQ',
    colClass: 'col-sm-6 col-4',
    onTrue: 'Yes',
    onFalse: 'No',
  },
  {
    type: 'checkbox',
    name: 'waterbike',
    id: 'sp15',
    label: 'Water Bike',
    colClass: 'col-sm-6 col-4',
    onTrue: 'Yes',
    onFalse: 'No',
  },
  {
    type: 'checkbox',
    name: 'swimingpool',
    id: 'sp16',
    label: 'Swimming Pool',
    colClass: 'col-sm-6 col-4',
    onTrue: 'Yes',
    onFalse: 'No',
  },
]

export const waterToys = [
  {
    type: 'textArea',
    name: 'watertoysdescription',
    id: 'wt1',
    label: 'WaterToys Description',
    colClass: 'col-sm-6 col-4',
    placeholder: 'Enter Description',
  },
  {
    type: 'select',
    name: 'scuba',
    id: 'wt2',
    label: 'Scuba',
    colClass: 'col-sm-6 col-4',
    placeholder: 'Select Scuba',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'text',
    name: 'snorkelgear',
    id: 'wt3',
    label: 'Snorkelgear',
    placeholder: 'Enter Snorkelgear',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'select',
    name: 'adultwaterskis',
    id: 'wt4',
    label: 'Adult Water Skis',
    colClass: 'col-sm-6 col-4',
    placeholder: 'Adult Water Skis',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'select',
    name: 'kidswaterskis',
    id: 'wt5',
    label: 'Kids Water Skis',
    placeholder: 'Select Kids Water Skis',
    colClass: 'col-sm-6 col-4',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'select',
    name: 'kneeboard',
    id: 'wt6',
    label: 'Knee Board',
    colClass: 'col-sm-6 col-4',
    placeholder: 'Select Knee Board',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'select',
    name: 'windsurfer',
    id: 'wt7',
    label: 'Wind surfer',
    colClass: 'col-sm-6 col-4',
    placeholder: 'Select Wind surfer',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'select',
    name: 'tube',
    id: 'wt8',
    label: 'Tube',
    colClass: 'col-sm-6 col-4',
    placeholder: 'Select Tube',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'select',
    name: 'scurfer',
    id: 'wt9',
    label: 'scurfer',
    colClass: 'col-sm-6 col-4',
    placeholder: 'Select Scurfer',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'select',
    name: 'wakeboard',
    id: 'wt10',
    label: 'Wakeboard',
    colClass: 'col-sm-6 col-4',
    placeholder: 'Select Wakeboard',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'select',
    name: 'onepersonkayak',
    id: 'wt11',
    label: 'One Person Kayak',
    colClass: 'col-sm-6 col-4',
    placeholder: 'Select One Person Kayak',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'select',
    name: 'twopersonkayak',
    id: 'wt12',
    label: 'Two Person Kayak',
    placeholder: 'Select One Person Kayak',
    colClass: 'col-sm-6 col-4',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'select',
    name: 'floatmats',
    id: 'wt13',
    label: 'Float Mats',
    colClass: 'col-sm-6 col-4',
    placeholder: 'Select Float Mats',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'select',
    name: 'fishinggear',
    id: 'wt14',
    label: 'Fishing Gear',
    colClass: 'col-sm-6 col-4',
    placeholder: 'Select Fishing Gear',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'text',
    name: 'tender',
    id: 'wt15',
    label: 'Tender',
    placeholder: 'Enter Tender',
    colClass: 'col-sm-6 col-4',
  },
  {
    type: 'select',
    name: 'tenderHorsepower',
    id: 'wt16',
    label: 'Tender Horse Power',
    placeholder: 'Select Tender Horse Power',
    colClass: 'col-sm-6 col-4',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'select',
    name: 'tenderpax',
    id: 'wt17',
    label: 'Tenderpax',
    placeholder: 'Select Tenderpax',
    colClass: 'col-sm-3 col-4',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'select',
    name: 'jetski',
    id: 'wt18',
    label: 'Jetski',
    placeholder: 'Select Jetski',
    colClass: 'col-sm-3 col-4',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'select',
    name: 'waverunner',
    id: 'wt19',
    label: 'Wave Runner',
    placeholder: 'Select Wave Runner',
    colClass: 'col-sm-3 col-4',
    options: [
      {
        label: 'Yes',
        value: 'Yes',
      },
      {
        label: 'No',
        value: 'No',
      },
    ],
  },
  {
    type: 'text',
    name: 'othertoys',
    id: 'wt20',
    placeholder: 'Enter Other Toys',
    label: 'Other Toys',
    colClass: 'col-sm-3 col-4',
  },
]
