export const myDummy = {
  general: {
    name: 'watertoys test yatch',
    fulldescription: 'test full description',
    height: '128',
    isnew: true,
    length: '1000',
    ownerid: {
      name: 'John Abrham',
      email: 'dasp78046@gmail.com',
      password: '$2a$10$.U45eQnmodb/TYAGxoQ2nuIicG74W/OqpEtWHqCneSrpBngpFqA1y',
      date: '2021-07-17T13:17:53.718Z',
      avathar: null,
      userType: 'Customer',
      _id: '60f2d88176ff44aa5337bb0d',
      updatedAt: '2021-09-06T04:07:28.266Z',
      createdAt: '2021-09-06T03:20:38.476Z',
      __typename: 'User',
    },
    point: '292',
    shortdescription: 'test short description',
    status: true,
    showonhomepage: true,
    typeid: '60e6a0bf92453bcb6417f723',
    typename: 'sample type name',
  },
  overview: {
    builder: "test builder",
    crew: "200",
    description: "overview description",
    gustes: "200",
    length: "112",
    refit: "2027-09-09",
    requirementsforthisBooking: ["cleanliness"],
    sleeps: "100",
    staterooms: "120",
    summer: "summer",
    winter: "winter",
    year: '2021'
  },
  specification:{
    bbq: true,
    beam: "232",
    bkings: "222",
    cruisingspeed: "450",
    engine: "test engine",
    enginebrand: "yamaha",
    enginefueltype: 'Diesel',
    enginehours: "322",
    enginemodel: "testmmodel",
    enginestotalpower: "1200hp",
    enginetype: "enginetype",
    fueldetails: "23",
    generators: "10",
    heads: "232",
    helicopterpad: true,
    jacuzzi: true,
    loa: "1202",
    maximumdraft: "23",
    queens: "122",
    sleeps: "222",
    specificationsdescription: "sample spec description",
    staterooms: "20",
    swimingpool: true,
    twins: "22",
  },
  watertoys:{
    windsurfer:'Yes',
    adultwaterskis: "Yes",
    fishinggear: "Yes",
    floatmats: "Yes",
    jetski: "Yes",
    kidswaterskis: "Yes",
    kneeboard: "Yes",
    onepersonkayak: "Yes",
    othertoys: "other toys",
    scuba: "Yes",
    scurfer: "Yes",
    snorkelgear: "snorkel gear",
    tender: "tender sample",
    tenderHorsepower: "Yes",
    tenderpax: "Yes",
    tube: "Yes",
    twopersonkayak: "Yes",
    wakeboard: "Yes",
    watertoysdescription: "water description",
    waverunner: "Yes",
  },
  charteragent:{
    displayorder: "2",
    facebook: "facebookurl",
    linkedin: "linkedinurl",
    name: "charter name",
    position: "2",
    twitter: "twitter handle",
    url: "my url",
    youtube:"youtube handle",
  },
  accomodation:{
    accommodationdescription:'this is a sample accomodation description', 
    accommodationfeatures:['sample1','sample2']
  }
}
